# Generated by Django 3.0 on 2020-05-03 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя чата')),
                ('category', models.CharField(choices=[('metal_and_rock', 'Металл и рок'), ('rap_and_pop', 'Реп и поп'), ('classic', 'Классика'), ('nightcore', 'Nightcore'), ('programming', 'Программирование'), ('2d', '2D графика'), ('3d', '3D графика'), ('design', 'Дизайн'), ('mmorpg', 'MMORPG'), ('rpg', 'RPG'), ('action', 'Экшон'), ('visual_novel', 'Визуальные новеллы'), ('anime', 'Аниме'), ('jojo', 'Джоджо'), ('manga', 'Манга'), ('ranobe', 'Ранобэ'), ('other', 'Другое')], default='Freshman', max_length=50, verbose_name='Категория чата')),
                ('is_private', models.BooleanField(verbose_name='Приватный чат')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания чата')),
            ],
        ),
        migrations.CreateModel(
            name='Messege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Ник')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Картинка сообщения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Chat')),
            ],
        ),
    ]
