# Generated by Django 3.0 on 2020-05-07 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messege',
            name='image',
        ),
        migrations.CreateModel(
            name='MessegeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='user_video/', verbose_name='Видео сообщения')),
                ('messege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Messege')),
            ],
        ),
        migrations.CreateModel(
            name='MessegeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/', verbose_name='Картинка сообщения')),
                ('messege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Messege')),
            ],
        ),
        migrations.CreateModel(
            name='MessegeAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='user_audio/', verbose_name='Аудио сообщения')),
                ('messege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Messege')),
            ],
        ),
    ]
