# Generated by Django 3.0 on 2020-05-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200507_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messegeimage',
            name='messege',
        ),
        migrations.RemoveField(
            model_name='messegevideo',
            name='messege',
        ),
        migrations.AddField(
            model_name='messege',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_images/', verbose_name='Файл сообщения'),
        ),
        migrations.DeleteModel(
            name='MessegeAudio',
        ),
        migrations.DeleteModel(
            name='MessegeImage',
        ),
        migrations.DeleteModel(
            name='MessegeVideo',
        ),
    ]
