# Generated by Django 3.0 on 2020-05-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200507_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messege',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_files/', verbose_name='Файл сообщения'),
        ),
    ]
