# Generated by Django 3.0 on 2020-05-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200507_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messege',
            old_name='image',
            new_name='file',
        ),
    ]
