# Generated by Django 3.0.6 on 2020-05-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200525_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Ник')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Chat')),
            ],
        ),
        migrations.DeleteModel(
            name='Messege',
        ),
    ]
